# Dependencies and docker images that can be used to setup a
# development environment for gridlook in combination with
# the information in Gemfile (gems, ruby version, etc).

dependencies:
  node: "0.10.30"

docker_services:
  postgres:
    image: "postgres:9.5.5"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/gridlook/postgres:/var/lib/postgresql/data"
