default: &default
  # Vagrant development box support
  <% if ENV["DEVBOX"] %>
  username: postgres
  password: dev
  host: localhost
  port: <%= `service_port postgres` %>
  <% else %>
  username: <%= ENV['USER'] %>
  password: <%= ENV['USER'] == "jenkins" ? 'jenkins' : nil %>
  <% end %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: gridlook_development
  pool: 5

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: gridlook_test
  <% if ENV["CIRCLECI"] %>
  username: postgres
  host: localhost
  <% end %>
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: gridlook_production
  pool: 5
