default:
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] || "fake_access_key_id" %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] || "fake_secret_access_key" %>
  region: <%= ENV["AWS_REGION"] || "eu-west-1" %>
